### ISSUE TITLE
New check: TODO or FIXME

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#175]
Would it be useful if dotenv-linter checked `.env` files for such words in comments: `TODO`, `FIXME`?

```bash
# TODO or todo
FOO=BAR

# FIXME or fixme
BAR=FO0
```

Please vote 👍or 👎

**Comment by mstruebing** [comment]
I personally don't think this is a good check to have.
If someone makes such a comment the person is aware of that and so the checker would fail if running in ci, maybe because it is even some thing that can not be fixed right now.

What would be your reasons to add this check? Maybe I'm missing a good case where it would be nice

**Comment by mgrachev** [comment]
I have seen this check in other linters. For example:
* https://github.com/golangci/golangci-lint/pull/621
* https://docs.codeclimate.com/docs/fixme

It is only proposal, so if this check doesn't be useful, I will close the issue 😃

**Comment by mstruebing** [comment]
Maybe other people think it is useful too, it's just my personal opinion and thoughts without further research :)

**Comment by mgrachev** [comment]
Okay, we will wait for other opinions.

Please vote 👍or 👎
