### ISSUE TITLE
Add fixer: EndingBlankLineFixer

### ISSUE THREAD

**Issue by DDtKey** [dotenv-linter/dotenv-linter#244]
Implement `trait Fix` to fix warnings caused by `EndingBlankLineChecker`.
And add this `Fix` to the `fixlist` in [fixes.rs](https://github.com/dotenv-linter/dotenv-linter/blob/cf176993360215596c079873725f4a4b7a48f5b0/src/fixes.rs#L32)

Implementation example: [LowercaseKeyFixer](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/fixes/lowercase_key.rs)

**Comment by baile320** [comment]
I was taking a look at this, and I'm running into an issue when implementing.

I was thinking something like this should work:
```
    fn fix_line(&self, line: &mut LineEntry) -> Option<()> {
        if line.is_last_line() && !line.raw_string.ends_with(LF) {
            line.raw_string.push_str("\n");
        }
        Some(())
    }
```
but what ends up happening is that if we have a file like, e.g.

```
ABC=DEF
FOO=BAR
THIS =THAT
```
The newline gets added by the THIS=THAT line gets completely deleted. I guess because of this line of code: https://github.com/dotenv-linter/dotenv-linter/blob/master/src/fs_utils.rs#L43, which isn't printing the final THIS=THAT line because it only goes to len()-1.

You can see the code I have here: https://github.com/baile320/dotenv-linter/tree/ending-blank-line-fixer and pull down to take a look at the behavior if you want, but I'm wondering if there's a simpler way to solve the issue apart from messing with the existing fs_utils (maybe you know off the top of your head, I'm just poking around :))

**Comment by evgeniy-r** [comment]
Hi! 
I think, I can help, but I'm little busy right now, I will write you later (maybe tomorrow).

**Comment by baile320** [comment]
Thank you! No hurry... I can probably find a few solutions, but I wouldn't be sure if there is a preferred one, so I appreciate the help 👍

**Comment by evgeniy-r** [comment]
Hello again!

When `Fix` trait was implemented (https://github.com/dotenv-linter/dotenv-linter/pull/228) I assumed that there are two groups of fixes: some can be implemented by working only with the line that caused warning, for others you need to work with the entire line collection.

I think that this fixer belongs to the secong group. So you can implement the `fix_warnings` method instead of the `fix_line` method and just append a blank line to the line collection.

This was the original idea. But maybe there is a better solution, if you find it, it will be interesting to discuss it.

**Comment by evgeniy-r** [comment]
We are modeling an ending blank line as a separate line entry: 
https://github.com/dotenv-linter/dotenv-linter/blob/612e1a96a0f1645dab1c9b16a2f0eddb2a9046a7/src/common.rs#L79

So I think it would be consistent to fix this warning by adding a separate line entry.

**Comment by baile320** [comment]
No, I think that makes sense and is much easier than what I was trying. Thanks for pointing me in the right direction!
